### ISSUE TITLE
Installing Pandas yield the following error...

### ISSUE THREAD

**Issue by Jephthah2018** [FKLC/IGQL#3] opened 2020-05-18 15:10 UTC
('Connection broken: OSError("(10054, \'WSAECONNRESET\')")', OSError("(10054, 'WSAECONNRESET')"))
I have been trying to install pandas, scipy and Jupyter and getting errors. The above popped up as I installed pandas. Iam using Miniconda. Anyone with an idea what I could do?

**Comment by FKLC** [comment] 2020-05-19 00:18
A problem like that happened before but it was fixed in #2. Unfortunately, I don't know the cause of the problem. This project is no longer active. I suggest you to using another library such as [Instaloader](https://github.com/instaloader/instaloader) or any alternative. If you think you have a solution please feel free to submit, but I can't help you with solving this problem, so I'm closing this issue, sorry.

**Closed as completed by FKLC** 2020-05-19 00:18 UTC
